name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout con todo el historial
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # IMPORTANTE: para reescribir ramas
          persist-credentials: true

      # 2. Generar el SVG de la serpiente
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: albadilop
          outputs: |
            dist/github-contribution-grid-snake.svg

      # 3. Configurar Git para el commit
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 4. Crear/actualizar la rama output y push forzado
      - name: Push to output branch
        run: |
          git checkout --orphan output      # crea o resetea la rama output
          git rm -rf .                      # limpia todos los archivos
          mkdir -p dist                     # asegura la carpeta dist
          cp -R dist/* .                    # copia el SVG al root
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake contribution graph"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
