name: Generate Snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create and switch to output branch
        run: |
          git fetch origin output || true
          git switch output || git switch --orphan output
          git reset --hard
          git clean -fdx

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: albadilop
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push changes
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake contribution SVG" || echo "No changes to commit"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
